### ISSUE TITLE
DeriveSchedulerContext.into(pageRequest); 处理完成以后程序不停止

### ISSUE THREAD

**Issue by ShrekerNil** [xtuhcy/gecco#106]
我在使用这个工具从某个网站上爬数据，我要的数据是异步加载的，所以我使用了loop等于true的方式，这个问题解决了，设置loop=false,然后notifyComplete就ok
但是在这个数据抓取到之后我手动`DeriveSchedulerContext.into(pageRequest);`，后面的数据抓取完成之后程序就停不了，这个如何处理？
![QQ截图20211118170717](https://user-images.githubusercontent.com/6695450/142385780-3df07ad2-3e2a-47d2-b6a3-5af2d27f4d0a.png)

**Comment by xtuhcy** [comment]
有start和run两个方式运行方式
