### ISSUE TITLE
关于爬虫中使用代理ip

### ISSUE THREAD

**Issue by heyinhenu** [xtuhcy/gecco#20]
当频繁的使用爬虫时候，某些网站会采取一些措施，是否会在代码中考虑加入代理ip？

**Comment by xtuhcy** [comment]
支持代理，代理ip需要自己提供，在classpath的根目录下定义proxys文件，每行表示一个代理服务器的主机和端口，如127.0.0.1:8888；

**Comment by heyinhenu** [comment]
3q  看来功能已经很完善了
