### ISSUE TITLE
What's the meaning of this ERROR? thx

### ISSUE THREAD

**Issue by XinlinFeng** [xtuhcy/gecco#27]
I have an error log as:
"ERROR com.geccocrawler.gecco.spider.Spider  - cant't match url : https://someurl
and Gecco shutdown after that:
2287 [GeccoEngine] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection manager is shutting down
2287 [GeccoEngine] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection manager shut down
2295 [GeccoEngine] INFO com.geccocrawler.gecco.GeccoEngine  - close gecco!
what's happening here? How can I solve this?

**Comment by xtuhcy** [comment]
GeccoEngine是start()还是run()？

**Comment by XinlinFeng** [comment]
我用的是start(),参照的是项目主页上面的例子

**Comment by xtuhcy** [comment]
加qq群，具体看看你的问题吧
