### ISSUE TITLE
不能设置User-Agent  ,Read timed out

### ISSUE THREAD

**Issue by jziver** [xtuhcy/gecco#28]
希望能增加读取失败后能循环重试
ERROR com.geccocrawler.gecco.spider.Spider:run(107) - com.geccocrawler.gecco.downloader.DownloadException: java.net.SocketTimeoutException: Read timed out

**Comment by xtuhcy** [comment]
user-agent可以配置文件设置userAgents放到classpath根目录，超时可以配置重试次数的GeccoEngine.retry
