### ISSUE TITLE
URL正则匹配以及动态生成字段问题

### ISSUE THREAD

**Issue by cookier** [xtuhcy/gecco#34]
1. URL正则匹配的问题
请问URL是否支持正则匹配？我自己测试下来是不支持的。

2. 动态生成字段问题
我指定生成一个`Integer`类型的`List`集合：`.listField("storiesId", Integer.class)`。
断点跟踪解析页面的值格式为：`Integer`数组。但是在`beanMap.put`赋值时，抛出异常`Object can not cast Integer`的类型转换异常。我将动态字段的类型改为`String`，也抛出转换异常。最后将类型改为`Object`才运行成功。请问集合字段只能设置为`Object`吗？

**Comment by xtuhcy** [comment]
1、由于考虑到正则使用的复杂性，没有放开URL的正则匹配。当然如果考虑到高级特性，后期可以放开。（待我评估一下是否需要放开）
2、listField是支持类型转换的，可以参考test里的DynamicJD类，.listField("details", productBrief).csspath("#plist .gl-item").build()。如果还有有问题你可以尝试先使用非动态方式定义bean，因为动态方式最终通过字节码编程转换为bean的
