### ISSUE TITLE
url不匹配是什么原因？

### ISSUE THREAD

**Issue by wzg723** [xtuhcy/gecco#35]
[Spider-0] WARN  o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Fri, 19 Jun 2037 08:57:04 -0000; secure; HttpOnly". Invalid 'expires' attribute: Fri, 19 Jun 2037 08:57:04 -0000
[Spider-0] ERROR c.g.gecco.spider.Spider - cant't match url : https://github.com/xtuhcy/gecco
运行了Quick start出现url不匹配问题，请问这是什么原因？谢谢~

**Comment by xtuhcy** [comment]
是不是你的classpath没有自定对，gecco会扫描你定义的classpath下的所有@Gecco注解
