### ISSUE TITLE
如何设置爬虫的超时时间

### ISSUE THREAD

**Issue by dh1314al** [xtuhcy/gecco#37]
int timeout = 1000;
if(context != null) {
currDownloader = context.getDownloader();
before = context.getBeforeDownload();
after = context.getAfterDownload();
timeout = context.getTimeout();
} else {
    currDownloader = engine.getSpiderBeanFactory().getDownloaderFactory().defaultDownloader();
}
if(before != null) {
    before.process(request);
}
HttpResponse response = currDownloader.download(request, timeout);

这段代码貌似是通过下载器去下载网页的，但是超时时间是硬编码写死的,有点不方便,可否开发一个接口让用户自己设置了

**Comment by xtuhcy** [comment]
@Gecco注解中有timeout的设置
