### ISSUE TITLE
JsonFieldRender渲染ajax请求返回的数据

### ISSUE THREAD

**Issue by jiapengfei** [xtuhcy/gecco#40]
这个ajax请求返回的数据应该是经过服务器端渲染的html片段，自己写了一个CustomFieldRender解析了其中的数据。
问题是每次请求，JsonFieldRender的Object json = JSON.parse(jsonStr)都会抛出异常c.g.gecco.spider.render.RenderException，看着有点不爽。。

**Comment by xtuhcy** [comment]
你的意思是ajax返回的json是一段html代码是吗？但是gecco不支持JsonBean嵌套套HtmlBean，所有你就自己实现一个自定义的是吗？这个问题新版本已经修改了，JsonBean里是可以嵌套HtmlBean的

**Comment by xtuhcy** [comment]
这个改动版本还没发布，我这两天发布一下

**Comment by jiapengfei** [comment]
ajax返回的json确实是一段html代码。期待新版本。

**Comment by xtuhcy** [comment]
1.2.10版本刚发布，可以试试看了
