### ISSUE TITLE
多线程设置无效

### ISSUE THREAD

**Issue by LiMingCH** [xtuhcy/gecco#58]
`        GeccoEngine.create()
                .classpath("com.wanshifu.customer.support.logger")
                .thread(8)
                .loop(false)
                .interval(1)
                .start("http://baojia.3hk.cn")
                .run();
`

![1522245625610](https://user-images.githubusercontent.com/9417001/38033848-8874b27e-32d3-11e8-88ce-0c0df9cadc7a.jpg)

**Comment by xtuhcy** [comment]
多线程需要对应多个startURL。你可以把http://baojia.3hk.cn的二级页面做完starturl加进来

**Comment by LiMingCH** [comment]
二级页面是在http://baojia.3hk.cn这个页面爬出来的，如果自己手动设置的话似乎与用爬虫的初衷有悖了。所以看看能不能通过一级页面抓到二级页面的链接之后自动启动多线程处理~
