### ISSUE TITLE
Spider 和 Scheduler 增强与拓展

### ISSUE THREAD

**Issue by Sunnus3** [xtuhcy/gecco#70]
你好,请问后期会不会增加对 Spider 和 Schedulter 拓展设置,目前我看源代码是直接在 GeccoEngine 中 new 相关对象,如果想要拓展必须通过修改 GeccoEngine 类来实现
哈哈,我主要是想增加一种拓展,类似 ScheduledThreadPoolExecutor 或者 Netty 中的 EventLoopGroup, 更自由方便的添加爬取任务

**Comment by Sunnus3** [comment]
其实主要是几个关键组件不方便自定义拓展或者是我没找到正确的打开方式

**Comment by xtuhcy** [comment]
欢迎pr，由于时间关系，目前没有计划修改~

**Comment by Sunnus3** [comment]
https://github.com/Sunnus3/gecco-schedule 我这两天改的,全是新增的代码,目前还没有大量的运行
