### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by Arugal** [xtuhcy/gecco#74]
https://github.com/xtuhcy/gecco/blob/44f3b390f83390f65688200e22394b83ad6d9a03/src/main/java/com/geccocrawler/gecco/downloader/HttpClientDownloader.java#L233-L254

如果入参InputStream为null, finally中instream.reset()会发生空指针异常

**Comment by indiefun** [comment]
是的，我这里使用的时候也碰到了，偶尔出现空指针异常，然后代理就不能正常回收，后续请求会出现无代理可用

**Comment by indiefun** [comment]
> 是的，我这里使用的时候也碰到了，偶尔出现空指针异常，然后代理就不能正常回收，后续请求会出现无代理可用

上述情况出现在使用默认的FileProxys的时候，因为FileProxys的实现使用了队列存储代理，getProxy的时候出队，failure/success的时候入队，如果不控制异常会导致后续请求都不能获取到代理

**Comment by xtuhcy** [comment]
> > 是的，我这里使用的时候也碰到了，偶尔出现空指针异常，然后代理就不能正常回收，后续请求会出现无代理可用
> 
> 上述情况出现在使用默认的FileProxys的时候，因为FileProxys的实现使用了队列存储代理，getProxy的时候出队，failure/success的时候入队，如果不控制异常会导致后续请求都不能获取到代理

异常没有捕获吗？

**Comment by indiefun** [comment]
当使用默认的FileProxys的时候，如果请求超时，抛出DownloadTimeoutException异常后，Spider.java的run函数catch到超时异常的时候会判断重新加入调度，此时的判断代码使用了getProxy会导致代理出队，然后没有回收，导致后续无代理可用。

**Comment by indiefun** [comment]
> > > 是的，我这里使用的时候也碰到了，偶尔出现空指针异常，然后代理就不能正常回收，后续请求会出现无代理可用
> > 
> > 
> > 上述情况出现在使用默认的FileProxys的时候，因为FileProxys的实现使用了队列存储代理，getProxy的时候出队，failure/success的时候入队，如果不控制异常会导致后续请求都不能获取到代理
> 
> 异常没有捕获吗？

HttpClientDownloader.java getContent 函数的参数 instream 是空指针，然后判断空指针放在了try里面，最后finnaly使用了这个空指针

**Comment by indiefun** [comment]
> 当使用默认的FileProxys的时候，如果请求超时，抛出DownloadTimeoutException异常后，Spider.java的run函数catch到超时异常的时候会判断重新加入调度，此时的判断代码使用了getProxy会导致代理出队，然后没有回收，导致后续无代理可用。

这个说的是另一个问题，今天也碰到了

**Comment by xtuhcy** [comment]
> > > > 是的，我这里使用的时候也碰到了，偶尔出现空指针异常，然后代理就不能正常回收，后续请求会出现无代理可用
> > > 
> > > 
> > > 上述情况出现在使用默认的FileProxys的时候，因为FileProxys的实现使用了队列存储代理，getProxy的时候出队，failure/success的时候入队，如果不控制异常会导致后续请求都不能获取到代理
> > 
> > 
> > 异常没有捕获吗？
> 
> HttpClientDownloader.java getContent 函数的参数 instream 是空指针，然后判断空指针放在了try里面，最后finnaly使用了这个空指针

改改？提个pr吧

**Comment by indiefun** [comment]
Arugal已经提了pr了，我就不提了
