### ISSUE TITLE
@Href如何判断获取到的多个a标签

### ISSUE THREAD

**Issue by avk458** [xtuhcy/gecco#81]
用List<String> 存Href，页面有两个翻页div，上面的div有4个a标签，下面的div有3个。两个div的className相同，如何在这长度为7的集合中判断下一页？

**Comment by xtuhcy** [comment]
目的是要判断下一页吗？当前页没有class区分？

**Comment by avk458** [comment]
@xtuhcy 没有区分，但是位置是固定的。用位置来取就可以了。谢谢，只是现在摸鱼都摸完了。
