### ISSUE TITLE
使用说明中抓取策略的深度和广度说法有误

### ISSUE THREAD

**Issue by peterxiemin** [xtuhcy/gecco#83]
---
通常爬虫需要一个有效管理下载地址的角色，Scheduler负责下载地址的管理。gecco对初始地址的管理使用StartScheduler，StartScheduler内部采用一个阻塞的FIFO的队列。初始地址通常会派生出很多其他待抓取的地址，派生出来的其他地址采用SpiderScheduler进行管理，SpiderScheduler内部采用线程安全的非阻塞FIFO队列。这种设计使的gecco对初始地址采用了深度遍历的策略，即一个线程抓取完一个初始地址后才会去抓取另外一个初始地址；对初始地址派生出来的地址，采用广度优先策略。
---
查看源码， 初始地址的抓取策略使用的是LinkedBlockingQueue，派生地址的抓取策略使用的ConcurrentSkipListSet，前置是一个队列，效果上应该是广度优先，后者是一个栈，效果上看是深度优先，感觉您在使用说明里将两种策略说反了。

**Comment by xtuhcy** [comment]
ConcurrentSkipListSet不是栈，是一个带优先级的set集合
