### ISSUE TITLE
matchUrl目前是否可以使用正则匹配呢？

### ISSUE THREAD

**Issue by wsosop** [xtuhcy/gecco#86]
例如：
现在有一个链接 ①为 ：http://www.xxx.cn/tool/index.jhtml
和另一个链接②为： http://www.xxx.cn/tool/4396.jhtml
需要从①的链接为爬取入口爬取②的页面，这两个链接分别该如何进行匹配呢？
是否可以使用正则呢？

**Comment by xtuhcy** [comment]
http://www.xxx.cn/tool/index.jhtml可以就这样写，这个写成http://www.xxx.cn/tool/{id}.jhtml
