### ISSUE TITLE
Pipeline之间如何优雅传值呢

### ISSUE THREAD

**Issue by Shkin1** [xtuhcy/gecco#87]
刚开始用,挺不错的框架.
使用过程中有以下几个问题:
1. 比如一个目录列表页Pipeline的处理结果, 我想传到详细页Pipeline的处理结果一起存储(关联), 目前除了将中间值存在URL中 传下去, 就想不到其他方式了
2. 目前官网上文档案例比较简单,复杂场景,还的自己多多尝

**Comment by xtuhcy** [comment]
1.可以用HttpRequest的addParameter方法将中间结果传到下一个pipeline
2.可以看看demo
