### ISSUE TITLE
List属性解析失败

### ISSUE THREAD

**Issue by aimilin6688** [xtuhcy/gecco#9]
List 内容如果是表格的每一行，会解析不到数据！
例如：`<tr> 
 <td>1</td> 
 <td>2</td> 
 <td>3</td> 
 <td>4</td> 
</tr>`  这样的html 内容，通过jsoup获取不到数据，jsuop将文本处理成`<html>
 <head></head>
 <body> 1 2 3 4 
 </body>
</html>`导致解析不到数据，希望作者修复下，谢谢

**Comment by xtuhcy** [comment]
这个问题是因为如果使用tr,td但是没有table包围，不符合html规范，jsoup会自动做一个转换。这个问题正在想办法处理

**Comment by aimilin6688** [comment]
我临时是这么处理的
`public HtmlParser(String baseUri, String content) {
		long beginTime = System.currentTimeMillis();
		log = LogFactory.getLog(HtmlParser.class);
		this.baseUri = baseUri;
		if (StringUtils.startsWithAny(content, "<tr", "<tr ")) {
			this.document = Jsoup.parse(content, baseUri, Parser.xmlParser());
		} else {
			this.document = Jsoup.parse(content, baseUri);
		}
		long endTime = System.currentTimeMillis();
		if (log.isTraceEnabled()) {
			log.trace("init html parser : " + (endTime - beginTime) + "ms");
		}
	}`

**Comment by xtuhcy** [comment]
已经解决，基本沿用你的思路，改成真正表达式。
