### ISSUE TITLE
starts.json not found

### ISSUE THREAD

**Issue by Huwei1993** [xtuhcy/gecco#91]
com.geccocrawler.gecco.GeccoEngine.startsJson(GeccoEngine.java:275) - starts.json not found

**Comment by Huwei1993** [comment]
<dependency>
            <groupId>com.geccocrawler</groupId>
            <artifactId>gecco</artifactId>
            <version>1.3.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.geccocrawler</groupId>
            <artifactId>gecco-spring</artifactId>
            <version>1.2.9</version>
        </dependency>

**Comment by yh1010** [comment]
> com.geccocrawler gecco 1.3.0 com.geccocrawler gecco spring 1.2.9

您好，这个是要更换版本吗

**Comment by xtuhcy** [comment]
不用，有什么问题？
