### ISSUE TITLE
document.select("#read_$$deptleaderIdea")

### ISSUE THREAD

**Issue by ttg432** [xtuhcy/gecco#95]
![image](https://user-images.githubusercontent.com/14066554/98649938-2e4de480-2373-11eb-8ae2-df006ef38881.png)

可以加层判断 如果id选择器获取内容得话，可以使用document.getElementById("read_$$deptleaderIdea").html()
如果使用用document.select("#read_$$deptleaderIdea") 对$符号得解析失败

**Comment by xtuhcy** [comment]
解析都是基于jsoup的

**Comment by xtuhcy** [comment]
可以提个pr
