### ISSUE TITLE
用gecco爬取app.mi.com会timeout，但是我用gecco自带的apache httpclient却没有这个问题

### ISSUE THREAD

**Issue by wxxlamp** [xtuhcy/gecco#98]
[INFO][2021-03-26 14:24:47 056][com.geccocrawler.gecco.downloader.proxy.FileProxys]-[proxys not load]
[INFO][2021-03-26 14:24:52 718][org.apache.http.impl.execchain.RetryExec]-[I/O exception (org.apache.http.conn.ConnectTimeoutException) caught when processing request to {s}->https://app.mi.com:443: Connect to app.mi.com:443 [app.mi.com/123.125.102.202, app.mi.com/111.202.1.247] failed: connect timed out]
[INFO][2021-03-26 14:24:52 736][org.apache.http.impl.execchain.RetryExec]-[Retrying request to {s}->https://app.mi.com:443]
[INFO][2021-03-26 14:24:54 753][org.apache.http.impl.execchain.RetryExec]-[I/O exception (org.apache.http.conn.ConnectTimeoutException) caught when processing request to {s}->https://app.mi.com:443: Connect to app.mi.com:443 [app.mi.com/123.125.102.202, app.mi.com/111.202.1.247] failed: connect timed out]
[INFO][2021-03-26 14:24:54 754][org.apache.http.impl.execchain.RetryExec]-[Retrying request to {s}->https://app.mi.com:443]
[INFO][2021-03-26 14:24:56 775][org.apache.http.impl.execchain.RetryExec]-[I/O exception (org.apache.http.conn.ConnectTimeoutException) caught when processing request to {s}->https://app.mi.com:443: Connect to app.mi.com:443 [app.mi.com/123.125.102.202, app.mi.com/111.202.1.247] failed: connect timed out]
[INFO][2021-03-26 14:24:56 781][org.apache.http.impl.execchain.RetryExec]-[Retrying request to {s}->https://app.mi.com:443]
[ERROR][2021-03-26 14:24:58 799][com.geccocrawler.gecco.spider.Spider]-[https://app.mi.com/category/1 ERROR : com.geccocrawler.gecco.downloader.DownloadTimeoutExceptionorg.apache.http.conn.ConnectTimeoutException: Connect to app.mi.com:443 [app.mi.com/123.125.102.202, app.mi.com/111.202.1.247] failed: connect timed out]
[INFO][2021-03-26 14:25:01 254][com.geccocrawler.gecco.GeccoEngine]-[close gecco!]

**Comment by xtuhcy** [comment]
是不是header什么的不一样

**Comment by wxxlamp** [comment]
应该是我的url写的有问题，https://app.mi.com/category/1#page=1，中间加了#好像一直timeout

**Comment by wxxlamp** [comment]
不过我换了个url就成功了
